name: Python CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          # Correspond à Python 3.12.1 (Actions permet "3.12", 3.12.1 n’est pas
          # toujours explicitement référencée, mais 3.12 pointe normalement vers
          # la dernière 3.12.x)
          python-version: '3.12'  

      - name: Upgrade pip + install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check code format with Black
        run: |
          pip install black==23.9.0
          # Vérifie uniquement (sans reformater) :
          black --check .

      - name: Lint code with Ruff
        run: |
          pip install ruff
          ruff check .

      - name: Run tests with Pytest
        run: |
          pytest
